feat(i18n): add cs-CZ translation
Emurgo/yoroi-mobile pull request #1257
Opened 2021-04-05 05:29 UTC by mychalvlcek

2021-04-05 05:32 UTC, SebastienGllmt commented
On CrowdIn, it looks like Czech translation hasn't been finished so I would avoid merging this PR until then

2021-04-06 09:17 UTC, v-almonacid requested changes
Thanks for your contribution! Apart from the detail I pointed out, it looks good. We'll definitely merge this once we have enough translations in crowdin.

2021-04-06 09:17 UTC, v-almonacid commented on src/i18n/locales/cs-CZ.json
> +  "components.common.languagepicker.czech": "Čeština",
All the `.../locales/xx-XX.json` files, except for `en-US.json`, shouldn't be touched—these are automatically generated by crowdin.

2021-04-08 23:37 UTC, mychalvlcek commented
@SebastienGllmt just finished translation

2021-04-09 08:04 UTC, v-almonacid commented
> @SebastienGllmt just finished translation

mhm what do you mean? I just checked CrowdIn and Czech is at 0%. Would you like to join and add the translations yourself? 😄

2021-04-09 16:02 UTC, mychalvlcek commented
> > @SebastienGllmt just finished translation
> 
> mhm what do you mean? I just checked CrowdIn and Czech is at 0%. Would you like to join and add the translations yourself? 😄


yes, thats what I did (or thought I did :D ),

is this correct link, right?

https://crowdin.com/project/yoroi-app/cs

2021-04-09 16:11 UTC, v-almonacid commented
> > > @SebastienGllmt just finished translation
> > 
> > 
> > mhm what do you mean? I just checked CrowdIn and Czech is at 0%. Would you like to join and add the translations yourself? 😄
> 
> yes, thats what I did (or thought I did :D ),
> 
> is this correct link, right?
> 
> https://crowdin.com/project/yoroi-app/cs

oh that's the Yoroi extension. Yoroi mobile has a separate Crowdin project https://crowdin.com/project/yoroi-mobile

2021-04-09 16:12 UTC, mychalvlcek commented
> > > > @SebastienGllmt just finished translation
> > > 
> > > 
> > > mhm what do you mean? I just checked CrowdIn and Czech is at 0%. Would you like to join and add the translations yourself? 😄
> > 
> > 
> > yes, thats what I did (or thought I did :D ),
> > is this correct link, right?
> > https://crowdin.com/project/yoroi-app/cs
> 
> oh that's the Yoroi extension. Yoroi mobile has a separate Crowdin project https://crowdin.com/project/yoroi-mobile

OK, don't have permissions to see this project, could you grant me somehow?

2021-04-09 16:28 UTC, v-almonacid commented
@mychalvlcek sure just send me an email address, or join our discord and I'll send you the invite there https://discord.gg/pstXdg5R

2021-04-13 21:24 UTC, mychalvlcek commented
Finally translation should be finished (except of terms of use)

2021-04-16 17:36 UTC, v-almonacid approved these changes

2021-04-16 17:37 UTC, merged

2021-04-16 17:39 UTC, v-almonacid commented
thank you @mychalvlcek ! note that if you want,  you can put your name in the `components.common.languagepicker.acknowledgement` key in crowdin, and your name/nickname will be in the initial screen.