add react-intl flow types
Emurgo/yoroi-mobile pull request #1346
Opened 2021-05-21 03:37 UTC by wolverineks

this removed a ton of `any`'s and revealed a ton of broken code
i've labelled each with a `$FlowFixMe` without any other modifications

2021-05-27 17:19 UTC, v-almonacid requested changes
Great work! Ii fpossible, you can add some additional fixes I suggested. But I realize there are many errors unveiled and probably I'll need to fix them myself in a separate PR.

2021-05-27 17:19 UTC, v-almonacid commented on package.json
> +    "flow-coverage-report": "^0.8.0",
we prefer to use exact versions 🙏

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Common/PinRegistrationForm.js
> +  pin: any,
maybe it's a good time to type those

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/DelegationConfirmation.js
> +              {/* $FlowFixMe */}
You can remove these by fixing the `Props` definition in `LedgerConnect`.  Just remove the `navigation` prop and make the `defaultDevices` prop optional, ie:
```
type Props = {|
  intl: IntlShape,
  defaultDevices?: ?Array<Device>, // for storybook
  onConnectUSB: (DeviceObj) => any,
  onConnectBLE: (DeviceId) => any,
  useUSB?: boolean,
  onWaitingMessage?: string,
  fillSpace?: boolean,
|}
```

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/DelegationConfirmation.js
> +        }: {intl: IntlShape} & Object) => async (_event) => {
Could you please add a `TODO` comment? we should type that correctly, but maybe in a follow up PR

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/DelegationConfirmation.stories.js
> +      // $FlowFixMe
for every `$FlowFixMe`, we try to always add an explanation as for why it's required. It may happen that we don't understand the reason, in this case it's also a good okay to add a comment, maybe another dev would know how to fix it.

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/StakingCenter.js
> +}: {intl: IntlShape} & Object) => {
please add a TODO comment here too

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/StakingDashboard.js
> +                  // $FlowFixMe
I'll fix these later, please add a TODO

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/WithdrawalDialog.js
> +          // $FlowFixMe
here we should just make `isUSBSupported` optional in `LedgerTransportSwitch`

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Delegation/WithdrawalDialog.js
> +          // $FlowFixMe
🙈

2021-05-27 17:19 UTC, v-almonacid commented on src/components/Ledger/LedgerConnect.js
> +          // $FlowFixMe
We can remove this just by removing the `?` in `defaultMessage` prop in `LocalizableError.js`

2021-05-27 17:19 UTC, v-almonacid commented on src/components/TxHistory/TxDetails.js
> +      {/* $FlowFixMe */}
please add a TODO comment here too

2021-05-27 17:19 UTC, v-almonacid commented on src/components/TxHistory/TxHistory.js
> +            // $FlowFixMe
🙈  TODO comment please

2021-05-27 17:19 UTC, v-almonacid commented
ahh also, if you can please fix the merge conflict :pray:

2021-05-28 16:02 UTC, wolverineks commented on src/components/Common/PinRegistrationForm.js
> +  pin: any,
ill type it in another pr

2021-06-01 10:30 UTC, v-almonacid approved these changes

2021-06-01 10:30 UTC, v-almonacid commented on src/components/UiKit/ScreenBackground.js
> +import React, {type ComponentType} from 'react'
Minor detail: According to our Style guide we group type instantiations at the end (after styles). No need to change it but to keep in mind. See README for more details

2021-06-01 10:31 UTC, merged