[wip] Revamp wallet screen
Emurgo/yoroi-mobile pull request #1608
Opened 2021-09-08 01:51 UTC by stackchain

2021-10-26 03:14 UTC, stackchain commented
/check

2021-10-27 05:01 UTC, wolverineks requested changes
no idea if any of this code works, or what its supposed to do
i could be more if you broke it up into smaller chunks with a focused purpose

2021-10-27 05:01 UTC, wolverineks commented on src/components/Spacer/index.tsx
> +export {default} from './Spacer'
avoid export default

2021-10-27 05:01 UTC, wolverineks commented on src/components/Spacer/Spacer.tsx
> +import type {ViewStyleProp} from 'react-native/Libraries/StyleSheet/StyleSheet'
this is not correct, react native typescript types are different than flow types,
delete them, then use auto import

2021-10-27 05:01 UTC, wolverineks commented on src/components/StylizedIcons/ReceivedIcon.tsx
> +export default memo<Props>(ReceivedIcon)
remove any `memo`'s that you come across

2021-10-27 05:01 UTC, wolverineks commented on src/components/StylizedIcons/SentIcon.tsx
> +export default memo<Props>(SentIcon)
same

2021-10-27 05:01 UTC, wolverineks commented on src/components/TxHistory/EmptyHistory.tsx
> +export default memo(EmptyHistory)
samee

2021-10-27 05:01 UTC, wolverineks commented on src/components/TxHistory/SyncErrorBanner.tsx
> +export default memo<Props>(SyncErrorBanner)
same

2021-10-27 05:01 UTC, wolverineks commented on src/components/TxHistory/TxHistory.stories.tsx
> +    <MockAppStateWrapper>
use `NavigationRouteContext.Provider` instead of actual navigators

2021-10-27 05:01 UTC, wolverineks commented on src/components/TxHistory/types.ts
> +// export type Transaction = {|
whats all this stuff?

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/ActionsBanner.tsx
> +    onSend: useCallback(() => navigation.navigate(WALLET_ROUTES.SEND), [navigation]),
why are you using `useCallback` here?

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/ActionsBanner.tsx
> +    onBuy: useCallback(() => Alert.alert(strings.messageBuy, strings.messageBuy), [strings.messageBuy]),
this isnt a navigation

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/ActionsBanner.tsx
> +export default memo(ActionsBanner)
remove all `memo`'s

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/BalanceBanner.tsx
> +            <Text style={styles.totalText}>{fiatTotalText}</Text>
render the text or dont render the text, but dont render an empty string

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/BalanceBanner.tsx
> +export default memo(BalanceBanner)
remove

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/BalanceBanner.tsx
> +  const onSwitchShowValues = useCallback(() => {
dont use `useCallback`

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/BalanceBanner.tsx
> +  const [balanceToShow, setBalance] = useState<string>('')
`[foo, setFoo]`

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/BalanceBanner.tsx
> +  useEffect(() => {
can you do this in render? why do you need a `useEffect`?

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/TabNavigator.tsx
> +export default memo<TabNavigatorProps>(TabNavigator)
remove all `memo`s

2021-10-27 05:01 UTC, wolverineks commented on src/components/WalletHero/WalletHero.tsx
> +const WalletHero = (props: WalletHeroProps) => {
what is `WalletHero`?

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/TabNavigator.js
> +          {tabs.map((label, i) => {
these tabs are known at runtime, so you dont need to map

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/TabNavigator.js
> +              <TouchableOpacity key={`tab-navigator-${i}`} style={styles.tabPanel} onPress={() => setActive(i)}>
avoid using index as key

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/ActionsBanner.js
> +  const onSend = useCallback(() => navigation.navigate(WALLET_ROUTES.SEND), [navigation])
you dont needd `useCallback` here

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/BalanceBanner.js
> +export default memo<mixed>(BalanceBanner)
remove

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/BalanceBanner.js
> +  const onSwitchShowValues = useCallback(() => {
you odnt need `useCallback` here

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/EmptyHistory.js
> +export default memo<mixed>(EmptyHistory)
remove

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/SyncErrorBanner.js
> +export default memo<Props>(SyncErrorBanner)
remove

2021-10-27 05:01 UTC, wolverineks commented on legacy/components/TxHistory/components/TabNavigator.js
> +export default memo<TabNavigatorProps>(TabNavigator)
remove

2021-10-27 05:01 UTC, wolverineks commented on src/components/Spacer/Spacer.tsx
> +export default memo<Props>(Spacer)
remove

2021-10-27 05:01 UTC, wolverineks commented on src/components/StylizedIcons/WalletAccountIcon.tsx
> +export default memo<Props>(WalletAccountIcon)
same

2021-10-28 02:33 UTC, stackchain commented on src/components/TxHistory/TxHistory.stories.tsx
> +    <MockAppStateWrapper>
https://github.com/Emurgo/yoroi-mobile/blob/revamp-wallet-screen/src/components/TxHistory/TxHistory.stories.tsx#L15

2021-10-31 20:22 UTC, merged