Transaction ui updates
Emurgo/yoroi-mobile pull request #1783
Opened 2021-11-18 02:40 UTC by stackchain

- Minor updates preparing for the pending transaction feature.

2021-11-18 14:04 UTC, wolverineks requested changes
remove error log, update gitignoree

2021-11-18 14:04 UTC, wolverineks commented on android/hs_err_pid13969.log
> +#
im guessing we should remove this file?

2021-11-18 14:04 UTC, wolverineks commented on src/TxHistory/WalletHero/TabNavigator.tsx
> +    fontFamily: Platform.select({
why do we need this? they are displaying the same font...

2021-11-18 14:04 UTC, wolverineks commented on src/TxHistory/WalletHero/BalanceBanner.tsx
> +    fontFamily: Platform.select({
do we need this if they are the same font?

2021-11-18 14:04 UTC, wolverineks commented on src/TxHistory/WalletHero/BalanceBanner.tsx
> +    fontFamily: Platform.select({
same

2021-11-19 00:36 UTC, stackchain commented on src/TxHistory/WalletHero/BalanceBanner.tsx
> +    fontFamily: Platform.select({
we don't famous ctrl+c/v, updating

2021-11-19 02:38 UTC, wolverineks approved these changes

2021-11-20 03:19 UTC, merged