Update faq menu option
Emurgo/yoroi-mobile pull request #1986
Opened 2022-05-20 09:59 UTC by jemubm

2022-05-20 17:19 UTC, stackchain commented on legacy/i18n/locales/en-US.json
> +  "menu.faqLink": "ASK OUR SUPPORT TEAM",
I'd suggest capitalizing on the view only.
```suggestion
  "menu.faqLink": "Ask our support team",
```

2022-05-20 17:20 UTC, stackchain commented on legacy/i18n/locales/en-US.json
> +  "menu.faqTitle": "Any Questions?",
I think we need to update the design.
```suggestion
  "menu.faqTitle": "Any question?",
```

2022-05-20 17:30 UTC, stackchain requested changes

2022-05-20 17:30 UTC, stackchain commented on src/Menu/Menu.tsx
> +import FaqImage from '../assets/img/icon/shape.png'
I'd suggest a name more specific, also please sync with design, to get `@2x` `@3x`, the high-resolution images.

2022-05-20 17:30 UTC, stackchain commented on yarn.lock
>  "@emurgo/cardano-serialization-lib-nodejs@^9.1.0":
I see this update in the `serialization-lib` used for the tests, but I don't see the update in the `package.json`, you can add the `package.json` or drop this file.

2022-05-23 14:08 UTC, stackchain commented on legacy/i18n/locales/en-US.json
> +  "menu.faqTitle": "Any Questions?",
I also believe that the text for the CTA is `Find answers on Yoroi Helpdesk`

2022-05-23 15:08 UTC, wolverineks requested changes

2022-05-23 15:08 UTC, wolverineks commented on src/Menu/Menu.tsx
> +import FaqImage from '../assets/img/icon/shape.png'
or svg

2022-05-23 15:08 UTC, wolverineks commented on src/Menu/Menu.tsx
> +
the spacing should be accomplished by using a `<Spacer fill />`

2022-05-23 15:08 UTC, wolverineks commented on src/Menu/Menu.tsx
> +import FaqImage from '../assets/img/icon/shape.png'
actually, see if you can get this to work
`<Icon.QuestionMark />`

2022-05-23 15:11 UTC, wolverineks commented on src/Menu/Menu.tsx
> +import FaqImage from '../assets/img/icon/shape.png'
and add it to the icon gallery story while youre at it :thumbsup:

2022-05-25 01:41 UTC, merged