Support ticket submission addition
Emurgo/yoroi-mobile pull request #1987
Opened 2022-05-20 16:05 UTC by jemubm

2022-05-20 17:17 UTC, stackchain requested changes

2022-05-20 17:17 UTC, stackchain commented on legacy/i18n/locales/en-US.json
> +  "components.walletselection.walletselectionscreen.supportTicketLink": "GET HELP ON YOROI HELPDESK",
I'd suggest capitalizing on the view only.
```suggestion
  "components.walletselection.walletselectionscreen.supportTicketLink": "Get help on Yoroi helpdesk",
```

2022-05-24 19:08 UTC, wolverineks approved these changes
start another pr on develop to clean this up after its been cherry-picked

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +    width: '100%',
avoid percentages

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +  linkTouchableOpacity: {
avoid using the component type when naming things
if we change the component type later, this will be confusing

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +    width: 235,
avoid fixed width, height

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +    width: 235,
this leads to cropping / overflow issues

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +    <View style={styles.linkContainer}>
prefer shorter names, avoid "container" names
`styles.link` > `styles.linkContainer`
there are exceptions

2022-05-24 19:08 UTC, wolverineks commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
> +const SUPPORT_TICKET_LINK = 'https://emurgohelpdesk.zendesk.com/hc/en-us/requests/new?ticket_form_id=360013330335'
colocate this next to the link component
make it as easy as possible to pull everything out into a separate file if necessary

2022-05-25 01:44 UTC, merged