Update installation instructions MAC users
Emurgo/yoroi-mobile pull request #1990
Opened 2022-05-23 08:31 UTC by jemubm

2022-05-26 07:31 UTC, Nebyt requested changes

2022-05-26 07:31 UTC, Nebyt commented on README.md
> +### Android Instalation
My suggestion is to move the whole section **Android installation** before the **Clone project**.

2022-05-26 07:31 UTC, Nebyt commented on README.md
> +- Install java 8:
Please add description How to switch between java versions for the case when a user has several Java versions on its machine.

2022-06-22 16:52 UTC, Nebyt approved these changes

2022-06-24 12:53 UTC, stackchain approved these changes
LGTM

2022-06-24 12:56 UTC, merged