feature: Added locked deposit
Emurgo/yoroi-mobile pull request #2013
Opened 2022-06-08 19:53 UTC by stackchain

2022-06-08 19:54 UTC, stackchain commented on src/TxHistory/LockedDeposit.tsx
> + * Important `minAdaRequired` is missing `has_hash_data`
Needs serialization lib v10

2022-06-13 13:12 UTC, wolverineks requested changes

2022-06-13 13:12 UTC, wolverineks commented on src/TxHistory/LockedDeposit.tsx
> +    <AlignHorizontal>
AlignHorizonal -> Row

2022-06-13 13:12 UTC, wolverineks commented on src/TxHistory/LockedDeposit.tsx
> +      const promises = utxosWithAssets.map(async (u) => {
can this be abstracted somewhere else?

2022-06-13 13:12 UTC, wolverineks commented on src/legacy/utils.ts
> +    let policyContent = await assets.get(policyId)
why was this necessary?

2022-06-13 13:12 UTC, wolverineks commented on src/yoroi-wallets/cardano/types.ts
> +  | 'asAddressedUtxo'
YoroiWallet should approach blockchain agnostic

2022-06-13 14:32 UTC, stackchain commented on src/legacy/utils.ts
> +    let policyContent = await assets.get(policyId)
Since one asset is a combination of `policyId` + `name`, it maps to build the `Value` object that minAda expects.

2022-06-13 16:24 UTC, jemubm approved these changes

2022-06-13 20:46 UTC, merged