[YOMO 166] App settings revamp
Emurgo/yoroi-mobile pull request #2050
Opened 2022-07-05 17:49 UTC by banklesss

https://user-images.githubusercontent.com/105349292/177879891-05530cf7-26ea-4e0f-baa3-a9e1546141ce.mov

2022-07-05 19:40 UTC, wolverineks requested changes

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const languageSelectedLabel = supportedLanguages.find((element) => element.code === languageCode)?.label
element -> language

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const languageSelectedLabel = supportedLanguages.find((element) => element.code === languageCode)?.label
keep all the language stuff together

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const {languageCode, supportedLanguages} = language
destructure inline

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const iconProps = {
move outside of component

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const languageSelectedLabel = supportedLanguages.find((element) => element.code === languageCode)?.label
move this into useLanguage
```
const { language } = use language()
...
label={language.label}
```

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  settings: {
move above messages

2022-07-05 19:40 UTC, wolverineks commented on src/Settings/SettingsItems.tsx
> +      <React.Fragment>
<React.Fragment> -> <>

2022-07-05 19:40 UTC, wolverineks commented on src/components/Hr/Hr.tsx
> +  return <View {...props} style={[styles.hr, {backgroundColor: lightPalette.gray['200']}]} />
merge props.styles into component style

2022-07-05 19:40 UTC, wolverineks commented on src/legacy/SettingsItems.tsx
> +    marginTop: 16,
avoid margin

2022-07-05 20:10 UTC, jemubm commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const languageSelectedLabel = supportedLanguages.find((element) => element.code === languageCode)?.label
Fixed. Thanks !

2022-07-05 20:11 UTC, banklesss commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const {languageCode, supportedLanguages} = language
Fixed. Thanks!

2022-07-05 20:13 UTC, jemubm commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  const iconProps = {
Done. Thanks!

2022-07-05 20:14 UTC, jemubm commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  settings: {
Done. Thanks!

2022-07-05 20:17 UTC, jemubm commented on src/Settings/SettingsItems.tsx
> +      <React.Fragment>
Done. Thanks!

2022-07-05 20:21 UTC, jemubm commented on src/components/Hr/Hr.tsx
> +  return <View {...props} style={[styles.hr, {backgroundColor: lightPalette.gray['200']}]} />
Done. Thanks!

2022-07-05 20:30 UTC, jemubm commented on src/legacy/SettingsItems.tsx
> +    marginTop: 16,
Done. Thanks!

2022-07-06 12:13 UTC, stackchain requested changes

2022-07-06 12:13 UTC, stackchain commented on src/Menu/Menu.tsx
> +          left={<Icon.Gear size={24} color="#6B7384" />}
Can we consume the color from the theme provider?

2022-07-06 12:13 UTC, stackchain commented on src/Settings/SettingsItems.tsx
> +            {fontFamily: 'Rubik', fontWeight: '400', color: lightPalette.gray['600'], fontSize: 14, lineHeight: 22},
Can we consume font from the theme provider?

2022-07-06 12:13 UTC, stackchain commented on src/Settings/SettingsItems.tsx
> +            {fontFamily: 'Rubik', fontWeight: '400', color: lightPalette['black-static'], fontSize: 16, lineHeight: 24},
⬆️

2022-07-06 12:13 UTC, stackchain commented on src/Settings/SettingsItems.tsx
> +              fontFamily: 'Rubik',
⬆️

2022-07-06 12:13 UTC, stackchain commented on src/Settings/SettingsItems.tsx
> +        fontFamily: 'Rubik',
⬆️

2022-07-06 12:13 UTC, stackchain commented on src/Settings/SettingsItems.tsx
> +                fontFamily: 'Rubik',
⬆️

2022-07-06 12:13 UTC, stackchain commented on src/components/Hr/Hr.tsx
> +    height: 1,
Perhaps leverage `StyleSheet.hairlineWidth`

2022-07-06 12:13 UTC, stackchain commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +  color: lightPalette.gray['600'],
To consume the theme, we are gonna need to be inside the theme provider context, perhaps move to inline stuff. 🤔

2022-07-06 12:17 UTC, jemubm commented on src/Menu/Menu.tsx
> +          left={<Icon.Gear size={24} color="#6B7384" />}
Hi Juliano, @wolverineks suggested do it in that way because the theme specifications are not fully defined

2022-07-06 12:31 UTC, wolverineks requested changes

2022-07-06 12:31 UTC, wolverineks commented on src/legacy/SettingsItems.tsx
> +const Touchable = (props: TouchableOpacityProps) => <TouchableOpacity {...props} activeOpacity={0.5} />
sort files with most important code at the top

2022-07-06 12:31 UTC, wolverineks commented on src/legacy/SettingsItems.tsx
> +const Touchable = (props: TouchableOpacityProps) => <TouchableOpacity {...props} activeOpacity={0.5} />
when possible

2022-07-06 12:31 UTC, wolverineks commented on src/i18n/LanguageProvider.tsx
>  type LanguageContext = {
```
type LanguageContext = {
  language,
  selectLanguageCode: SaveLanguageCode
  supportedLanguages: SupportedLanguages
}
```

2022-07-06 12:32 UTC, wolverineks commented on src/i18n/LanguageProvider.tsx
>  type LanguageContext = {
```
const { language } = useLanguage()
...
language.code
langauge.label
```

2022-07-06 12:51 UTC, jemubm commented on src/i18n/LanguageProvider.tsx
>  type LanguageContext = {
Changed. Thanks!

2022-07-06 12:53 UTC, banklesss commented on src/legacy/SettingsItems.tsx
> +const Touchable = (props: TouchableOpacityProps) => <TouchableOpacity {...props} activeOpacity={0.5} />
@wolverineks, in that file there are components shared by other files. So it can be an exception right?

2022-07-06 13:15 UTC, wolverineks requested changes

2022-07-06 13:15 UTC, wolverineks commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +                console.log('balance hiding switch click!')
remove logging

2022-07-06 13:15 UTC, wolverineks commented on src/i18n/LanguageProvider.tsx
> +const getLanguageLabel = (languageCode: LanguageCode): LanguageLabel =>
inline

2022-07-06 13:15 UTC, wolverineks commented on src/legacy/SettingsItems.tsx
> +const Touchable = (props: TouchableOpacityProps) => <TouchableOpacity {...props} activeOpacity={0.5} />
typically, if its not exported, i put it toward the bottom

2022-07-06 13:23 UTC, jemubm commented on src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
> +                console.log('balance hiding switch click!')
Done

2022-07-06 13:23 UTC, banklesss commented on src/legacy/SettingsItems.tsx
> +const Touchable = (props: TouchableOpacityProps) => <TouchableOpacity {...props} activeOpacity={0.5} />
Done

2022-07-06 13:36 UTC, jemubm commented on src/i18n/LanguageProvider.tsx
> +const getLanguageLabel = (languageCode: LanguageCode): LanguageLabel =>
Done

2022-07-06 16:48 UTC, stackchain approved these changes

2022-07-06 18:21 UTC, stackchain requested changes
@jemubm one thing that I forgot to mention, `crowdin` will delete other file keys based on `en-US`, otherwise it will end up in conflicts if you update the other languages, so please revert that updates on the translation files and keep only the update on `en-US`.

2022-07-06 18:22 UTC, jemubm commented
> @jemubm one thing that I forgot to mention, `crowdin` will delete other file keys based on `en-US`, otherwise it will end up in conflicts if you update the other languages, so please revert that updates on the translation files and keep only the update on `en-US`.

I will do thanks!

2022-07-06 22:35 UTC, jemubm commented
@stackchain The translations files has been reverted

2022-07-08 14:26 UTC, jemubm commented on src/components/Hr/Hr.tsx
> +    height: 1,
Done

2023-07-31 18:02 UTC, closed without merging

2023-07-31 18:03 UTC, banklesss commented
Resurrected here -> https://github.com/Emurgo/yoroi/pull/2563