fix ledger transactions
Emurgo/yoroi-mobile pull request #2094
Opened 2022-08-05 03:49 UTC by wolverineks

2022-08-08 01:24 UTC, stackchain requested changes

2022-08-08 01:24 UTC, stackchain commented on src/HW/HW.stories.tsx
> +  // ))
```suggestion
```

2022-08-08 01:24 UTC, stackchain commented on src/HW/HW.stories.tsx
> +      {error && <Text>error: {error.message}</Text>}
```suggestion
      {error != null && <Text>error: {error.message}</Text>}
```

2022-08-08 01:24 UTC, stackchain commented on src/HW/mocks.ts
> +  },
```suggestion
```

2022-08-08 01:24 UTC, stackchain commented on src/yoroi-wallets/cardano/unsignedTx.ts
> +  const rewardAddressRegExp = /^[ef]?[0-9a-fA-F]+$/i
Do only reward addresses take uppercase hex?

2022-08-08 01:24 UTC, stackchain commented on src/yoroi-wallets/cardano/unsignedTx.ts
> +export const toBech32 = (address: string) => {
Can we have a test for this?

2022-08-12 20:29 UTC, wolverineks commented on src/yoroi-wallets/cardano/unsignedTx.ts
> +export const toBech32 = (address: string) => {
nope

2022-08-15 12:16 UTC, stackchain requested changes

2022-08-15 12:16 UTC, stackchain commented on src/yoroi-wallets/cardano/ShelleyWallet.ts
>      const signedLedgerTx = await signTxWithLedger(ledgerPayload, this.hwDeviceInfo, useUSB)
signTxWithLedger -> signTxWithLedger

2022-08-15 12:16 UTC, stackchain commented on src/yoroi-wallets/cardano/unsignedTx.ts
> +const isPointerAddress = (address: string) => ['4', '5'].includes(address.charAt(0))
`0x[4]1` = `A`, `0x[4]4` = `D`, `A` = `Byron`, `D` = `Dead/Icarus`
It needs to check for byron first, that's the only way.
https://github.com/Emurgo/yoroi-frontend/blob/9a29a38cf69b7d4472a94615c9255101b318c74e/packages/yoroi-extension/app/api/ada/lib/storage/bridge/utils.js#L277

2022-08-15 15:55 UTC, wolverineks commented on src/yoroi-wallets/cardano/ShelleyWallet.ts
>      const signedLedgerTx = await signTxWithLedger(ledgerPayload, this.hwDeviceInfo, useUSB)
?

2022-08-15 16:30 UTC, stackchain commented on src/yoroi-wallets/cardano/ShelleyWallet.ts
>      const signedLedgerTx = await signTxWithLedger(ledgerPayload, this.hwDeviceInfo, useUSB)
shadowing

2022-08-16 15:40 UTC, wolverineks commented on src/yoroi-wallets/cardano/ShelleyWallet.ts
>      const signedLedgerTx = await signTxWithLedger(ledgerPayload, this.hwDeviceInfo, useUSB)
ill change it in another pr

2022-08-22 19:39 UTC, stackchain approved these changes

2022-08-22 19:39 UTC, merged