Send feature isolate data
Emurgo/yoroi-mobile pull request #2097
Opened 2022-08-10 15:33 UTC by jemubm

2022-08-11 13:17 UTC, stackchain requested changes

2022-08-11 13:17 UTC, stackchain commented on src/TxHistory/TxHistoryNavigator.tsx
> +          {() => <AddressReaderQR />}
component={AddressReaderQR}

2022-08-11 13:35 UTC, jemubm commented on src/TxHistory/TxHistoryNavigator.tsx
> +          {() => <AddressReaderQR />}
Done. Thanks!

2022-08-11 21:16 UTC, merged

2022-08-12 15:06 UTC, wolverineks commented on src/Send/SendScreen/SendScreen.stories.tsx
> +  mockWallet.subscribe = () => undefined
avoid mutation

2022-08-12 16:08 UTC, stackchain commented on src/Send/SendScreen/SendScreen.stories.tsx
> +  mockWallet.subscribe = () => undefined
https://github.com/Emurgo/yoroi-mobile/pull/2099/files#diff-f23eed79018887d6a48987da7c5dad5e046e85e1ed98d15964c483d70c3252c5R17