Removing exponential formatting for large numbers
Emurgo/yoroi-mobile pull request #2100
Opened 2022-08-12 20:08 UTC by jemubm

2022-08-12 20:53 UTC, wolverineks approved these changes

2022-08-14 16:27 UTC, stackchain requested changes

2022-08-14 16:27 UTC, stackchain commented on src/Send/SendScreen/SendScreen.tsx
>                tokenBalance.get(selectedTokenIdentifier) || new BigNumber('0'),
```suggestion
              tokenBalance.get(selectedTokenIdentifier) ?? new BigNumber('0'),
```

2022-08-14 16:31 UTC, jemubm commented on src/Send/SendScreen/SendScreen.tsx
>                tokenBalance.get(selectedTokenIdentifier) || new BigNumber('0'),
Thanks!

2022-08-14 16:40 UTC, stackchain approved these changes

2022-08-14 16:54 UTC, merged