Wallet removing refactor
Emurgo/yoroi-mobile pull request #2113
Opened 2022-08-24 17:08 UTC by jemubm

2022-08-24 17:39 UTC, stackchain requested changes
What was the issue? I'm guessing if the `walletMeta` is in sync with the selected wallet.

2022-08-24 17:39 UTC, stackchain commented on src/Catalyst/Step4.tsx
> +          keyId: walletManager.id,
```suggestion
          keyId: walled.id,
```

2022-08-24 17:39 UTC, stackchain commented on src/Catalyst/Step4.tsx
> +      const decryptedKey = await KeyStore.getData(walletManager.id, 'MASTER_PASSWORD', '', password, intl)
```suggestion
      const decryptedKey = await KeyStore.getData(wallet.id, 'MASTER_PASSWORD', '', password, intl)
```

2022-08-24 17:39 UTC, stackchain commented on src/components/ConfirmTx/ConfirmTx.tsx
> +            const decryptedKey = await KeyStore.getData(walletManager.id, 'MASTER_PASSWORD', '', password, intl)
```suggestion
            const decryptedKey = await KeyStore.getData(wallet.id, 'MASTER_PASSWORD', '', password, intl)
```

2022-08-24 17:39 UTC, stackchain commented on src/yoroi-wallets/walletManager.ts
> +  async removeCurrentWallet(walletId: YoroiWallet['id']) {
I've updated our docs, walletId: string -> YoroiWallet['id']
```suggestion
  async removeWallet(walletId: YoroiWallet['id']) {
```

2022-08-24 19:47 UTC, jemubm commented
> What was the issue? I'm guessing if the `walletMeta` is in sync with the selected wallet.

The wallet manager `_id` property is a wallet `id` copy, and we are using both separately. I think this could be a problem.

I am checking if there may be any desynchronization with the `walletMeta` at some point but I have not found it yet. If I found something I would open a new PR

2022-08-24 19:48 UTC, jemubm commented on src/Catalyst/Step4.tsx
> +          keyId: walletManager.id,
Thanks!

2022-08-25 05:24 UTC, wolverineks commented
should this be merging into rc3?

2022-08-25 15:20 UTC, stackchain commented
> should this be merging into rc3?

I don't think so.

2022-08-25 16:39 UTC, closed without merging

2022-08-25 16:40 UTC, jemubm commented
Closing. Changes don't needed.