Removing await from wallet closing
Emurgo/yoroi-mobile pull request #2131
Opened 2022-09-02 21:40 UTC by jemubm

2022-09-04 23:59 UTC, stackchain requested changes

2022-09-04 23:59 UTC, stackchain commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
>        }
remove try catch

2022-09-04 23:59 UTC, stackchain commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
>          resetToWalletSelection()
```suggestion
```

2022-09-05 14:49 UTC, jemubm commented on src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
>        }
Done.

2022-09-05 15:22 UTC, wolverineks approved these changes

2022-09-05 15:25 UTC, merged