Close wallet refactor
Emurgo/yoroi-mobile pull request #2157
Opened 2022-09-21 21:45 UTC by jemubm

2022-09-22 00:11 UTC, wolverineks commented on src/hooks/index.ts
> +import {useFocusEffect, useNavigation} from '@react-navigation/native'
this file shouldn't have any react native stuff in it, out shouldn't have anything yoroi-mobile specific in it

2022-09-22 00:13 UTC, wolverineks commented on src/hooks/index.test.ts
> +// Hack!! The following native modules are breaking the test
which test?

2022-09-22 00:18 UTC, wolverineks requested changes

2022-09-22 00:18 UTC, wolverineks commented on src/hooks/index.ts
> +      selectWalletMeta(walletMeta)
pass aaaaallllll of this stuff in as parameters

2022-09-23 13:22 UTC, closed without merging

2022-09-23 13:23 UTC, jemubm commented
A simpler fix wil be applied.