Change YoroiNFT and TokenInfo data structure
Emurgo/yoroi-mobile pull request #2461
Opened 2023-05-05 15:36 UTC by MichalSzorad

Resolves YOMO-458

2023-05-05 16:05 UTC, michalszorad commented
This is put on hold until we resolve the token info encoding issue YOMO-539 to confirm the new data structure works.

2023-05-11 18:35 UTC, michalszorad commented
I'm looking into resolving the conflicts

2023-05-11 23:33 UTC, jemubm reviewed
I have a question

Don't we need to define "hybrid" tokens in this case?

2023-05-11 23:46 UTC, jemubm commented on apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
> +    .sort((a, b) => sortNfts(a.name ?? '', b.name ?? ''))
👍🏻

2023-05-11 23:47 UTC, jemubm commented on apps/wallet-mobile/src/legacy/format.ts
if there are useful thing here, should they be moved to another place?

2023-05-12 13:04 UTC, michalszorad commented
Good point @jemubm I'll look into that

2023-05-12 19:04 UTC, stackchain requested changes

2023-05-12 19:04 UTC, stackchain commented on apps/wallet-mobile/src/yoroi-wallets/types/tokens.ts
> +  name?: string
name can be empty '' but can't be undefined.

2023-05-17 06:56 UTC, michalszorad commented
@jemubm we'll leave hybrid for now and use only FT/NFT as there are some unknowns and need to be discussed with Ruslan

2023-05-18 16:32 UTC, michalszorad commented on apps/wallet-mobile/src/yoroi-wallets/types/tokens.ts
> +  ticker: string | undefined
@stackchain @jemubm would it make sense to add `author` and `files` properties here for the NFT object? We're accessing these on the NFT detail screen / nft preview

2023-05-19 13:57 UTC, banklesss commented on apps/wallet-mobile/src/features/Send/common/filterBySearch.ts
> +      if (name) return name.toLowerCase().includes(searchTermLowerCase)
`toLocaleLowerCase ` ?

2023-05-19 14:08 UTC, banklesss commented on apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
> +          {isEmptyString(name) ? '-' : name}
i remember @stackchain asked me to add this logic to the top

2023-05-21 10:29 UTC, michalszorad commented on apps/wallet-mobile/src/yoroi-wallets/types/tokens.ts
> +  name?: string
That's now updated

2023-05-21 10:29 UTC, michalszorad commented on apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
> +          {isEmptyString(name) ? '-' : name}
I've moved this up

2023-05-21 10:29 UTC, michalszorad commented on apps/wallet-mobile/src/features/Send/common/filterBySearch.ts
> +      if (name) return name.toLowerCase().includes(searchTermLowerCase)
I've removed the toLowerCase, as it was lowercased twice

2023-05-22 17:10 UTC, jemubm approved these changes

2023-05-22 20:32 UTC, stackchain approved these changes

2023-05-22 20:32 UTC, stackchain approved these changes

2023-05-22 20:38 UTC, merged