Use intl to format date and remove moment
Emurgo/yoroi-mobile pull request #2476
Opened 2023-05-19 09:29 UTC by MichalSzorad

Resolves YOMO-470

2023-05-19 09:29 UTC, michalszorad commented on apps/wallet-mobile/package.json
> -    "moment": "2.29.1",
Remove moment

2023-05-19 09:30 UTC, michalszorad commented on apps/wallet-mobile/src/legacy/format.ts
> +export const formatDateAndTime = (timestamp: string, intl: IntlShape) => {
Refactored function name, removed `any` and changed variable name from `ts` to `timestamp`

2023-05-19 09:31 UTC, michalszorad commented on apps/wallet-mobile/src/legacy/format.ts
> +  if (inputDateString === yesterday) {
Not sure if there's a better way to check today / yesterday without using moment

2023-05-22 17:44 UTC, jemubm approved these changes

2023-05-22 20:00 UTC, stackchain commented on apps/wallet-mobile/src/legacy/format.ts
> +export const formatTime = (timestamp: string, intl: IntlShape) => {
since it's expecting a string and it can be empty, I'd say it should be validated here, `.length === 0 => ''`, and not in every call.

2023-05-22 20:24 UTC, stackchain commented on apps/wallet-mobile/src/legacy/format.ts
> +  if (inputDateString === yesterday) {
Why `.toDateString()` ?
```
function getYesterday() {
    const date = new Date();
    date.setDate(date.getDate() - 1);
    return date.toISOString().split('T')[0];
}
```

2023-05-22 20:25 UTC, stackchain requested changes
⬆️

2023-05-23 14:23 UTC, michalszorad commented on apps/wallet-mobile/src/legacy/format.ts
> +export const formatTime = (timestamp: string, intl: IntlShape) => {
I've added an empty string check. However, the caller will need to check for null | undefined, as this fn accepts string only

2023-05-23 15:48 UTC, merged