e2e first test ios
Emurgo/yoroi-mobile pull request #2556
Opened 2023-07-28 09:39 UTC by rahulnair87

1) revived tests for iOS
2) manage locators separately for iOS and Android if needed
3) added utils

2023-07-31 11:33 UTC, Nebyt requested changes

2023-07-31 11:33 UTC, Nebyt commented on apps/wallet-mobile/e2e/screens/restoreWalletFlow.screen.ts
> +// export const walletNameInput = () =>  element(by.type(`android.widget.EditText`)).atIndex(0)
Please remove these commented lines

2023-07-31 11:33 UTC, Nebyt commented on apps/wallet-mobile/e2e/screens/restoreWalletFlow.screen.ts
> +// export const repeatSpendingPasswordInput = () => element(by.type(`android.widget.EditText`)).atIndex(2)
Please remove these commented lines

2023-07-31 11:33 UTC, Nebyt commented on apps/wallet-mobile/e2e/tests/_ios/create-wallet.test.ts
> +       // await device.enableSynchronization()
Please remove these lines if we don't need it

2023-07-31 11:33 UTC, Nebyt commented on apps/wallet-mobile/e2e/tests/_ios/create-wallet.test.ts
> +       // await device.enableSynchronization()
Please remove these lines if we don't need it

2023-07-31 12:57 UTC, rahulnair87 commented on apps/wallet-mobile/e2e/screens/restoreWalletFlow.screen.ts
> +// export const repeatSpendingPasswordInput = () => element(by.type(`android.widget.EditText`)).atIndex(2)
done. thanks

2023-07-31 12:57 UTC, rahulnair87 commented on apps/wallet-mobile/e2e/tests/_ios/create-wallet.test.ts
> +       // await device.enableSynchronization()
done thanks

2023-07-31 13:14 UTC, rahulnair87 commented on apps/wallet-mobile/e2e/tests/_ios/create-wallet.test.ts
> +       // await device.enableSynchronization()
done

2023-07-31 14:34 UTC, Nebyt approved these changes

2023-07-31 14:34 UTC, Nebyt commented on apps/wallet-mobile/package.json
> +    "run:ios:yoroi:debug": "ENVFILE=.env react-native run-ios --mode=Debug --scheme=yoroi --verbose",
I don't think we need to do that

2023-08-01 05:04 UTC, rahulnair87 commented on apps/wallet-mobile/package.json
> +    "run:ios:yoroi:debug": "ENVFILE=.env react-native run-ios --mode=Debug --scheme=yoroi --verbose",
Yeah, you are right. Reverted

2023-08-02 22:05 UTC, merged