chore(tests): Add E2E NFT gallery tests
Emurgo/yoroi-mobile pull request #2592
Opened 2023-08-07 14:37 UTC by rahulnr7

1) test for searching in gallery by nft name
2) add test IDs
3) add utils

2023-08-07 15:28 UTC, Nebyt requested changes

2023-08-07 15:28 UTC, Nebyt commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        await expect(nftGalleryScreen.cardNFT(nftToSearch)).toBeVisible()
This check will pass even the search will not work.
I mean search will not search anything and displayed nfts will stay the same as before.
I would suggest to add check for amount of found NFTs and after that check that the found nft is that we are looking for.

2023-08-07 15:28 UTC, Nebyt commented on apps/wallet-mobile/e2e/tests/_ios/search-nft-gallery.test.ts
> +        await expect(nftGalleryScreen.cardNFT(nftToSearch)).toBeVisible()
The same remark as for android test.

2023-08-07 15:37 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        await expect(nftGalleryScreen.cardNFT(nftToSearch)).toBeVisible()
I thought it will say 'No NFTs found' if no match, no? or is there a case when the search inouts does not result in any filtering?

2023-08-08 12:22 UTC, Nebyt commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        await expect(nftGalleryScreen.cardNFT(nftToSearch)).toBeVisible()
> a case when the search inouts does not result in any filtering

This one

2023-08-08 15:03 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        await expect(nftGalleryScreen.cardNFT(nftToSearch)).toBeVisible()
new approach was adopted

2023-08-09 08:02 UTC, Nebyt requested changes

2023-08-09 08:02 UTC, Nebyt commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +            exit = true
It can be replaced with `return true`

2023-08-09 08:02 UTC, Nebyt commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         exit = true
It can be replaced `return false`

2023-08-09 08:02 UTC, Nebyt commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +   return matched
This part can be removed after adding `return` statement before.
I would suggest to use a proper logging tool into file instead of console logging.

2023-08-09 09:47 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +   return matched
Done. Yes, we have one to add it to the html report - addMsgToReport() in utils.

2023-08-09 09:47 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         exit = true
Done

2023-08-09 09:47 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +            exit = true
Done

2023-08-09 11:24 UTC, Nebyt approved these changes

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +   /** @type {Detox.ElementAttributes} */
This type annotation can be removed

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         nftAttributes = await element(by.id(/^card_nft_[a-zA-Z0-9_ ]+$/)).atIndex(i).getAttributes()
We won't have to define the `nftAttributes` type if we use const inside the loop

```
const nftAttributes = ...
if ('label' in nftAttributes) {
 // ... 
}
```

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        const nftCount =await nftGalleryScreen.countNftsDisplayedAndroid()
It looks like the file is not formatted

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         exit = true
would a `break` instead of `exit = true` work here?

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/screens/devOptionsScreen.screen.ts
> +export const btnResetAnalyticsConsent = () => element(by.id('btnResetAnalyticsConsent'))
I see sometimes we use `button` and sometimes `btn`. Would it be better to use always one?

2023-08-10 07:42 UTC, michalszorad commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +export const countNftsDisplayedAndroid = async (max = 10) => {
Why is there a different function for Android and iOS? Is it possible to reuse one function?

2023-08-10 10:38 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +   /** @type {Detox.ElementAttributes} */
Done. Thanks!

2023-08-10 10:38 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         nftAttributes = await element(by.id(/^card_nft_[a-zA-Z0-9_ ]+$/)).atIndex(i).getAttributes()
Done, Thanks

2023-08-10 10:39 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +         exit = true
Done, Thanks

2023-08-10 10:39 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/tests/_android/search-nft-gallery.test.ts
> +        const nftCount =await nftGalleryScreen.countNftsDisplayedAndroid()
Done, Thanks

2023-08-10 10:40 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/devOptionsScreen.screen.ts
> +export const btnResetAnalyticsConsent = () => element(by.id('btnResetAnalyticsConsent'))
Done, Thanks

2023-08-10 10:40 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/devOptionsScreen.screen.ts
> +export const btnResetAnalyticsConsent = () => element(by.id('btnResetAnalyticsConsent'))
Yes will stick to using button and camel case

2023-08-10 10:48 UTC, rahulnr7 commented on apps/wallet-mobile/e2e/screens/nftGallery.screen.ts
> +export const countNftsDisplayedAndroid = async (max = 10) => {
Detox behaves differently for iOS and Android in certain instances(not fully evolved for Android yet). 
In this case, if we try to find the matching elements for a locator that is a regular expression, then for iOS, the getAttributes() returns an array of objects while for Android it fails with multiple matching elements found error. 
So for Android the way to find the total number of matching elements will be to index the returned value iteratively till it fails to find next one.

2023-08-10 12:41 UTC, michalszorad approved these changes

2023-08-10 13:37 UTC, merged