Feat ramp on of design funnel
Emurgo/yoroi-mobile pull request #2939
Opened 2023-12-14 08:57 UTC by lehuyaa

2023-12-18 11:01 UTC, jorbuedo commented on .yarnrc
How is this created? Should it be ignored?

2023-12-18 11:01 UTC, jorbuedo commented on .yarn/releases/yarn-1.22.15.cjs
How is this created? Should it be ignored?

2023-12-18 11:08 UTC, jorbuedo commented on apps/wallet-mobile/ios/yoroi/AppDelegate.mm
Could you explain what's this for?

2023-12-18 11:08 UTC, jorbuedo commented on apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
Could you explain what's this for?

2023-12-19 08:39 UTC, lephuochoai commented on apps/wallet-mobile/ios/yoroi/AppDelegate.mm
I added some lines of code to open the app through your Banxa return link.

2023-12-19 08:39 UTC, lephuochoai commented on .yarn/releases/yarn-1.22.15.cjs
I will remove it

2023-12-19 08:40 UTC, lephuochoai commented on .yarnrc
I will remove it

2023-12-19 09:20 UTC, lephuochoai commented on apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
Sorry, this file has been changed by Xcode; we will revert it.

2023-12-19 09:20 UTC, lehuyaa commented on .yarn/releases/yarn-1.22.15.cjs
yes, we can ignore it, i will remove it and push on this branch

2023-12-19 09:20 UTC, lehuyaa commented on .yarnrc
yes, we can ignore it, i will remove it and push on this branch

2023-12-19 09:22 UTC, lehuyaa commented on apps/wallet-mobile/ios/yoroi/AppDelegate.mm
This is a auto generated file and it does not affect the flow, I will remove it

2023-12-19 09:22 UTC, lehuyaa commented on apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
This is a auto generated file and it does not affect the flow, I will remove it

2023-12-19 12:39 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/common/AmountCard/AmountCard.stories.tsx
> +        console.log('VALUE', value)
it can be replace by `action` from storybook addons

2023-12-19 12:40 UTC, stackchain commented on apps/wallet-mobile/src/assets/img/banner-buy-ada.png
replace the PNGS for SVGS (can be exported directly from Figma as SVG), resize based on a `zoom` property

2023-12-19 13:01 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/common/DescribeAction.tsx
> +const BANXA_SUPPORT_URL = 'https://support.banxa.com/en/support/home'
@SorinC6 can you expose this link through the banxa module?

2023-12-19 13:11 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/CreateRampOnOffScreen/EditAmount/EditAmount.tsx
> +  const balance = useBalance({wallet, tokenId: ''})
wallet.primaryTokenInfo.id

2023-12-19 13:11 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/CreateRampOnOffScreen/EditAmount/EditAmount.tsx
> +      amount={{tokenId: '', quantity: balance}}
⬆️

2023-12-19 13:12 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/CreateRampOnOffScreen/ProviderFee/ProviderFee.tsx
> +      <Text style={styles.text}>{`${2}%`}</Text>
@SorinC6 please check the % if it's correct.

2023-12-19 13:12 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/CreateRampOnOffScreen/ProviderFee/ProviderFee.tsx
> +export default ProviderFee
prefer named exports

2023-12-19 13:12 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/CreateRampOnOffScreen/EditAmount/EditAmount.tsx
> +export default EditAmount
~~prefer named exports~~ we will be updating it later

2023-12-19 13:15 UTC, stackchain commented on apps/wallet-mobile/src/features/RampOnOff/useCases/StartRampOnOff/ResultExchangeScreen/ResultExchange.tsx
> +  const {coin, coinAmount, fiat, fiatAmount} = params ?? {}
params are unsafe, please leverage useParams + typeguard for the expected types.

2023-12-19 13:21 UTC, stackchain requested changes
tiny CR

2023-12-20 09:01 UTC, stackchain approved these changes

2023-12-20 09:37 UTC, merged