refactor(catalyst): revamp + dark theme
Emurgo/yoroi-mobile pull request #3410
Opened 2024-07-18 08:14 UTC by banklesss

## Description / Change(s) / Related issue(s)

##### Ticket

YOMO-1676

TO-DO

- [ ] Extract shared state to @yoroi/staking  package

2024-07-18 08:20 UTC, michalszorad commented on apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
> +    if (unsignedTx.unsignedTx.catalystRegistrationData && onCIP36SupportChange) {
Hello, is this to change the order of the screens and show the QR code before signing the tx?

2024-07-18 08:22 UTC, banklesss commented on apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
> +    if (unsignedTx.unsignedTx.catalystRegistrationData && onCIP36SupportChange) {
that change is implemented to be able to update the unsigned tx object i case of CIP36 support changes when connecting the hardware wallet

2024-07-18 08:26 UTC, banklesss commented on apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
> +    if (unsignedTx.unsignedTx.catalystRegistrationData && onCIP36SupportChange) {
that piece of code has been literally copied from the old confirm tx component

2024-07-18 08:31 UTC, banklesss commented on apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
> +    if (unsignedTx.unsignedTx.catalystRegistrationData && onCIP36SupportChange) {
so this is a temporal implementation

2024-07-18 08:32 UTC, jorbuedo commented on apps/wallet-mobile/translations/messages/src/legacy/Catalyst/DownloadCatalyst.json
> +<<<<<<< Updated upstream
Conflicts

2024-07-18 12:05 UTC, stackchain commented on apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
> +  console.log('getCardanoAppMajorVersion-1')
```suggestion
```

2024-07-18 12:05 UTC, stackchain commented on apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
> +  console.log('getCardanoAppMajorVersion-2')
```suggestion
```

2024-07-18 12:10 UTC, stackchain commented on packages/staking/src/catalyst/translators/state.tsx
> +  pin: string | null
Pin typed is an input, it should match with Pin generated, I'd say to create as a full input state, touched, error ....

2024-07-18 12:11 UTC, stackchain requested changes
lgtm, 1 point related the PIN input

2024-07-18 16:37 UTC, banklesss commented on packages/staking/src/catalyst/translators/state.tsx
> +  pin: string | null
@stackchain I have kept those variables local because they are only used in that component and are not shared by any other component

Please tell me if you have any questions about it or can you suggest any improvements

2024-07-19 09:55 UTC, stackchain approved these changes

2024-07-19 09:55 UTC, merged