feat(wallet-mobile): Add network switch support to dApp explorer
Emurgo/yoroi-mobile pull request #3483
Opened 2024-08-02 09:53 UTC by michaeljscript

## Description / Change(s) / Related issue(s)

Add network switch support to dApp explorer

##### Ticket

[YOMO-1807](https://emurgo.atlassian.net/jira/software/c/projects/YOMO/issues/YOMO-1807)

[YOMO-1807]: https://emurgo.atlassian.net/browse/YOMO-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-02 13:42 UTC, stackchain reviewed
⬆️

2024-08-02 13:42 UTC, stackchain commented on apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
> +    chainId: 450,
hey @michaeljscript chainId is protocol level it should be 0 | 1 AFAIK, the previous network id was deprecated in favor of network, that is 'sancho' 'mainnet' and 'preprod' Im guessing this is what u r lf

2024-08-02 15:51 UTC, michalszorad commented on apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
> +    chainId: 450,
Many thanks @stackchain   What number should a sancho wallet return for `api.getNetworkId(): Promise<number>` in the [CIP-30](https://cips.cardano.org/cip/CIP-30)?

2024-08-02 16:44 UTC, michalszorad commented on apps/wallet-mobile/src/components/ChainWarning/ChainWarning.tsx
> +export const ChainWarning = ({title, description, onClose}: Props) => {
I've moved this out of Pool screens, as the layout is shared across multiple screens

2024-08-02 16:47 UTC, michalszorad commented on apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
> +    chainId: 450,
Will use 0

2024-08-02 18:12 UTC, banklesss commented on apps/wallet-mobile/src/components/ChainWarning/ChainWarning.tsx
> +export const ChainWarning = ({title, description, onClose}: Props) => {
should this component have a generic name?

2024-08-02 22:17 UTC, michalszorad commented on apps/wallet-mobile/src/components/ChainWarning/ChainWarning.tsx
> +export const ChainWarning = ({title, description, onClose}: Props) => {
Good point. I've renamed it to `GradientWarning`, let me know if you have any better idea 😄

2024-08-05 07:49 UTC, stackchain commented on apps/wallet-mobile/src/components/ChainWarning/GradientWarning.tsx
> +      position: 'relative',
```suggestion
      ...atoms.overflow_hidden,
      ...atoms.relative,
      borderRadius: 8,
```

2024-08-05 07:49 UTC, stackchain commented on apps/wallet-mobile/src/components/ChainWarning/GradientWarning.tsx
> +      position: 'absolute',
```suggestion
      ...atoms.absolute,
```

2024-08-05 07:49 UTC, stackchain commented on apps/wallet-mobile/src/components/ChainWarning/GradientWarning.tsx
> +      zIndex: 1,
```suggestion
      ...atoms.z10,
```

2024-08-05 07:58 UTC, stackchain requested changes
looking solid, minor styling updates

2024-08-05 07:58 UTC, stackchain commented on apps/wallet-mobile/src/features/Discover/common/BrowserProvider.tsx
> +  const storageId = wallet?.id != null ? `${wallet.id}-${network}` : null
@michaeljscript, if used the wallet.accountStorage (I dunno if it is exposed), you can check on <wallet>.build, you can use a key such as `browserProvider` it will take care of the `path`, by joining `<root>/legacy/<network>/v1/<wallet-id>/accounts/<account>/`

2024-08-05 07:58 UTC, stackchain commented on apps/wallet-mobile/src/features/Discover/common/BrowserProvider.tsx
> +  const storageId = wallet?.id != null ? `${wallet.id}-${network}` : null
network-manager now build the storage for the wallet (join at the root for all data related to the network)

2024-08-05 07:58 UTC, stackchain commented on apps/wallet-mobile/src/features/Discover/common/useDAppsConnected.tsx
> +    queryKey: [wallet.id, 'dappsConnected', wallet.networkManager.network],
```suggestion
    queryKey: [wallet.id, 'useDappsConnected', wallet.networkManager.network],
```

2024-08-05 07:58 UTC, stackchain commented on apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
> +  return useQuery({queryFn: () => getTxDetails(cbor), useErrorBoundary: true, queryKey: ['txDetails', cbor]})
```suggestion
  return useQuery({queryFn: () => getTxDetails(cbor), useErrorBoundary: true, queryKey: ['useTxDetails', cbor]})
```

2024-08-05 07:58 UTC, stackchain commented on apps/wallet-mobile/src/features/Search/SearchContext.tsx
> +      <Icon.Cross size={20} color={color.gray_cmax} />
icons should use `el_gray_....`

2024-08-05 08:44 UTC, michalszorad commented on apps/wallet-mobile/src/features/Discover/common/BrowserProvider.tsx
> +  const storageId = wallet?.id != null ? `${wallet.id}-${network}` : null
Hmm, the suggested storage, however, stores data on the storage, is that correct? Here, we use only memory storage because one of the requirements was to wipe tabs when the app is closed.

2024-08-05 12:39 UTC, stackchain commented on apps/wallet-mobile/src/features/Discover/common/BrowserProvider.tsx
> +  const storageId = wallet?.id != null ? `${wallet.id}-${network}` : null
aaa Roger

2024-08-05 12:39 UTC, stackchain approved these changes

2024-08-05 12:39 UTC, merged