add build version, network and commit hash in settings
Emurgo/yoroi-mobile pull request #709
Opened 2019-08-14 18:25 UTC by v-almonacid

This is currently how this PR look like (without much effort trying to match the specified design).

![image](https://user-images.githubusercontent.com/7271744/63045806-67c64480-bed1-11e9-92a1-06d14bfde45b.png)

Notes for the reviewer:

-  In particular, please check the way the commit hash is retrieved (through the `get_commit.sh` script and then using ` react-native-config` to read the commit hash as a config variable . I'd have loved to find a cleaner way. Perhaps just hard coding it the same way the version number is specified?
- This PR adds an additional dependency (`react-native-device-info`) to get the version number.

2019-08-15 22:56 UTC, nicarq requested changes
the UI looks good! but I would make it part of the building process, so `get_commit` is executed in every build. I maybe I could do the setup for iOS and you for Android?

2019-08-15 23:16 UTC, nicarq commented on package.json
> +    "android-mainnet-debug": "yarn run pre-packager && react-native run-android --variant=mainDebug",
I would delete this. This is too hacky, because it doesn’t work for releases.

2019-08-15 23:17 UTC, nicarq commented on package.json
> +    "pre-packager": "./get_commit.sh",
this should be part of `Gradle` and `Xcode` rather than `package.json`

2019-08-16 04:21 UTC, nicarq commented on package.json
> +    "android-mainnet-debug": "yarn run pre-packager && react-native run-android --variant=mainDebug",
So basically, I would focus in making it work for the `fastlane` deployment scripts

2019-08-16 09:02 UTC, v-almonacid commented
Right! Actually I forgot to mention that this was only a proposal and that the releasing process was not addressed yet. All the part related to getting the commit hash seemed a bit too hacky and I wanted to have your feedback before going further.

2019-08-16 18:02 UTC, v-almonacid commented
@nicarq it took me a while to figure out but I think it's much better now. Basically every Gradle task of type release or debug install will be executed after a `:app:getCurrentCommitHash` task. So this  task will be executed before every release with fastlane and also before every `react-native run-android ...` build. What do yo think?

Let me know if you are going to take care of the iOS part, or I'll do it ;)

2019-08-16 19:44 UTC, nicarq commented
@v-almonacid that sounds pretty good! Could you take a look at iOS? I started doing some stuff, but I didn’t finish 😁 I can explain what I learn along the way

2019-08-21 20:09 UTC, v-almonacid commented
@nicarq this PR should be now ready for final review.

2019-08-22 09:41 UTC, nicarq approved these changes

2019-08-22 09:41 UTC, merged