replace rust encryption/decryption by js module emip3js
Emurgo/yoroi-mobile pull request #722
Opened 2019-10-26 15:27 UTC by v-almonacid

The new Shelley rust libraries do not include encryption/decryption functions (due to design reasons), so these are now implemented in JS (see [emip3js](https://github.com/Emurgo/emip3js)). This PR just replaces the rust functions by the new JS functions.

Note: I still need to add a few more tests in emip3js so don't merge yet.

2019-10-28 07:59 UTC, v-almonacid commented on src/crypto/customPin.js
> +export const encryptCustomPin = async (installationId: string, pin: string) => {
(nothing changed here)

2019-10-31 20:54 UTC, nicarq requested changes
this seems good to me, but I would like to be 100% that we are compatible with previous encryptions -- if not we would do a migration. Could u write a test to validate this?

2019-11-01 11:00 UTC, v-almonacid commented
@nicarq You are right, I checked this locally by compiling the rust implementation and checking if both JS and rust were compatible. Just added a unit test 😉

2019-11-01 19:10 UTC, nicarq approved these changes

2019-11-01 19:10 UTC, merged